## Python code for week 1

In [1]:
import numpy as np

---   

### Q1b. Backward substitution code

In [13]:
def MyBackSub(A,b):
    n=len(b)
    x=np.zeros(n)
    x[n-1]=b[n-1]/A[n-1, n-1]
    for i in range(n-2,-1,-1):
        s=A[i,i+1:]@x[i+1:]
        x[i]=(b[i] - s)/A[i, i]
    return x

# Example for A upper triangular
A = np.array([[1.0, -1.0,1.0],
              [0.0, 5.0,-4.0],
              [0.0, 0.0, 2.0]])

b = np.array([2.0, 1.0, 2.0])

# Compare results
solution_python = MyBackSub(A, b)
solution_numpy = np.linalg.solve(A, b)

print("MyBacSub solution: ", solution_python)
print("NumPy solution:    ", solution_numpy)

MyBacSub solution:  [2. 1. 1.]
NumPy solution:     [2. 1. 1.]


---   

### Q1c. Forward substitution code

In [16]:
def MyForwSub(A,b):
    n=len(b)
    x=np.zeros(n)
    
    x[0]=b[0]/A[0, 0]
    
    for i in range(1, n):
        s = A[i,:i]@x[:i]
        x[i]=(b[i]-s)/A[i,i]
    return x

# Example for A lower triangular
A = np.array([[2.0, 0.0, 0.0],
              [3.0, 1.0, 0.0],
              [5.0, 2.0, 1.0]])

# Example random RHS
b=np.random.rand(3)

# Compare results
solution_python = MyForwSub(A,b)
solution_numpy = np.linalg.solve(A,b)

print("MyForwSub solution:", solution_python)
print("NumPy's solution:  ", solution_numpy)

MyForwSub solution: [ 0.26938707 -0.10757364 -1.12150797]
NumPy's solution:   [ 0.26938707 -0.10757364 -1.12150797]


---   

### Q2c. LU factorisation  

In [17]:
def MyLU(A):
    n=A.shape[0]
    U=A.copy().astype(float)
    L=np.eye(n, dtype=float)

    for c in range(n-1):
        for i in range(c+1,n):
            L[i,c]=U[i, c]/U[c,c]
            U[i,c]=0
            for j in range(c+1,n):
                U[i,j]=U[i, j]-L[i, c]*U[c, j]
    return L,U

# Example from question
A = np.array([[1.0, 0.0, 3.0, 1.0],
              [1.0, 1.0, 1.0, 0.0],
              [0.0, 2.0, 0.0, 0.0],
              [2.0, 1.0, 0.0, 1.0]])

L, U = MyLU(A)

print("Original Matrix A:")
print(A)

print("\nLower Triangular L:")
print(L)

print("\nUpper Triangular U:")
print(U)

A_reconstructed = L @ U

print("\nVerification (L @ U):")
print(A_reconstructed)


Original Matrix A:
[[1. 0. 3. 1.]
 [1. 1. 1. 0.]
 [0. 2. 0. 0.]
 [2. 1. 0. 1.]]

Lower Triangular L:
[[ 1.  0.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  2.  1.  0.]
 [ 2.  1. -1.  1.]]

Upper Triangular U:
[[ 1.  0.  3.  1.]
 [ 0.  1. -2. -1.]
 [ 0.  0.  4.  2.]
 [ 0.  0.  0.  2.]]

Verification (L @ U):
[[1. 0. 3. 1.]
 [1. 1. 1. 0.]
 [0. 2. 0. 0.]
 [2. 1. 0. 1.]]


---   

### Q2d. LU factorisation with forward & backward substitution

In [18]:
# Here we just use previous functions so...
A = np.array([[1.0, 0.0, 3.0, 1.0],
              [1.0, 1.0, 1.0, 0.0],
              [0.0, 2.0, 0.0, 0.0],
              [2.0, 1.0, 0.0, 1.0]])
b=np.array([4.0, 3.0, 4.0, 7.0])
L,U=MyLU(A);
y=MyForwSub(L,b)
x=MyBackSub(U,y)
print("x=",x)

x= [1. 2. 0. 3.]


---   

### Q3c. LU factorisation with partial pivoting.  

---   

In [22]:
def MyLUPP(A):
    n=A.shape[0]
    U=A.copy().astype(float)
    L=np.eye(n, dtype=float)
    p=np.arange(n)

    for c in range(n - 1):

        # the permutation part
        s = np.argmax(np.abs(U[c:,c]))+c
        
        U[[c,s],:]=U[[s,c],:]
        p[[c,s]]=p[[s,c]]
        if c > 0:
            L[[c,s],:c] = L[[s,c],:c]

        for i in range(c+1, n):
            L[i,c]=U[i,c]/U[c,c]
            U[i,c]=0.0
            for j in range(c+1,n):
                U[i,j]=U[i,j]-L[i,c]*U[c,j]
    return L,U,p

# Example from question
A = np.array([[0.0, 1.0, -2.0, 2.0],
              [2.0, 0.0, 2.0, 2.0],
              [1.0, 1.0, -1.0, 2.0],
              [0.0, 0.0, 1.0, 0.0]])

L,U,p = MyLUPP(A)

print("Original Matrix A:\n",A); 
print("\nLower Triangular L:\n",L)
print("\nUpper Triangular U:\n",U)
print("\nPermutation vector p:\n",p)

Original Matrix A:
 [[ 0.  1. -2.  2.]
 [ 2.  0.  2.  2.]
 [ 1.  1. -1.  2.]
 [ 0.  0.  1.  0.]]

Lower Triangular L:
 [[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.5 1.  0.  1. ]]

Upper Triangular U:
 [[ 2.  0.  2.  2.]
 [ 0.  1. -2.  2.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]

Permutation vector p:
 [1 0 3 2]
